[package]
name = "file-tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2.5.0"
calamine = "0.26.1"
clap = "4.5.20"
rayon = "1.10.0"
rust_xlsxwriter = "0.80.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
